### ISSUE TITLE
列表项backspace后崩溃

### ISSUE THREAD

**Issue by liuwei77** [solidoc/issues#3]
在列表中的某一项右侧单击，出现block selection的光标，然后连续backspace，每次删除一个列表项，当删除最后一个列表项后崩溃。

**Comment by liuwei77** [comment]
使用鼠标框选全部list子节点，按backspace/delete/mod+x都导致崩溃

**Comment by justtio** [comment]
**完善delete action逻辑：**
1. 当选择删除某个节点的所有子节点时，判断此节点是否为悬空节点并递归查询父级节点是否为悬空节点。若父节点非悬空节点时，应该删除节点本身；若父级节点为悬空节点，找到第一个非悬空节点，并删除该节点。
2. 当删除节点的父级节点为editor时，应抛出自定义错误类型告知前端进行下一步操作。

**ps悬空节点:** 无sibling且无自身text节点的递归嵌套节点。

**Comment by justtio** [comment]
已解决
